name: API Test Workflow (LanaCoin)

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    # No permissions needed as it doesn't commit files

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # Only dependency for the test script

      - name: Run API Test Script
        id: test
        env:
          # Pass the repository secret CRYPTOID_API_KEY as API_KEY env variable
          # Script will run even if key is missing, but key-required endpoints will fail/be skipped
          API_KEY: ${{ secrets.CRYPTOID_API_KEY }}
        run: |
          # Run the test script - output will go to workflow logs
          python api_test_script.py

