# .github/workflows/archive_report.yml

name: Archive Daily Whale Report

# Controls when the workflow will run
on:
  # Schedule to run daily at 03:00 UTC (adjust as needed)
  schedule:
    - cron: '0 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # 1. Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use latest version

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5 # Use latest version
        with:
          python-version: '3.10' # Specify your Python version

      # 3. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib numpy # Add any other dependencies your script needs

      # 4. Run the report generation script
      #    Assumes generate_report_html.py prints HTML to stdout and saves PNGs
      #    Make sure your API key is stored as a secret named LANA_API_KEY in your repo settings
      - name: Generate Report and Images
        run: python generate_report_html.py > LANA_Whale_Report.html
        env:
          API_KEY: ${{ secrets.LANA_API_KEY }} # Pass the API key as an environment variable

      # 5. Create Release and Upload Assets using GitHub CLI
      - name: Create Release and Upload Assets
        run: |
          # Generate a tag name based on the current date
          TAG_NAME="report-$(date +'%Y-%m-%d')"
          echo "Creating release with tag: $TAG_NAME"

          # Create the release and upload files.
          # Adjust the list of files at the end to match exactly what your script generates!
          # If your HTML embeds images, you might only upload LANA_Whale_Report.html
          gh release create "$TAG_NAME" \
             --title "Lana Whale Report - $(date +'%Y-%m-%d')" \
             --notes "Automated daily whale report for $(date +'%Y-%m-%d')." \
             LANA_Whale_Report.html \
             top_holders_chart.png \
             lorenz_curve.png \
             balance_histogram.png
        env:
          # GITHUB_TOKEN is automatically available to the workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

