name: Run LanaCoin Analysis

on:
  schedule:
    # Example: Run daily at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to push changes back to the repo
    permissions:
      contents: write # Needed to commit changes back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use latest major version

      - name: Set up Python
        uses: actions/setup-python@v5 # Use latest major version
        with:
          python-version: '3.10' # Specify a concrete Python version (e.g., 3.10)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install requests, needed by analysis.py
          pip install requests
          # Optional: Use requirements.txt if you create one
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests; fi

      - name: Run Analysis Script
        # Runs the script and redirects standard output to analysis_output.md
        # The script itself now saves address_transactions.json
        id: analysis
        env:
          # Pass the repository secret CRYPTOID_API_KEY as API_KEY env variable
          API_KEY: ${{ secrets.CRYPTOID_API_KEY }}
        run: |
          # Execute python script, redirecting stdout (report) to a file
          python analysis.py > analysis_output.md
          # Check if output file was created and has content
          if [ ! -s analysis_output.md ]; then
            echo "Analysis script report (stdout) is empty." >&2
          else
            echo "Analysis script finished and produced report output."
          fi
          # Also check if the JSON file was created by the script
          if [ ! -f address_transactions.json ]; then
             echo "Warning: address_transactions.json file not found." >&2
          else
             echo "Found address_transactions.json file."
          fi

      - name: Commit results
        # Commits both the report and the raw JSON data
        if: true # Ensure this step runs
        run: |
          # Configure git user for commit
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Define the report file to be updated in the repository
          TARGET_REPORT_FILE="RESULTS.md"
          # Define the JSON data file created by the script
          JSON_DATA_FILE="address_transactions.json"

          echo "Copying analysis report output to $TARGET_REPORT_FILE"
          # Copy the script's stdout output to the target report file
          cp analysis_output.md $TARGET_REPORT_FILE || echo "analysis_output.md not found, skipping copy."

          # Add both the report file and the JSON data file to git staging
          echo "Adding $TARGET_REPORT_FILE and $JSON_DATA_FILE to git"
          git add $TARGET_REPORT_FILE $JSON_DATA_FILE

          echo "Checking for changes..."
          # Commit only if there are changes staged in tracked files
          # Use git status --porcelain to check for any changes
          if output=$(git status --porcelain) && [ -z "$output" ]; then
            echo "No changes detected to commit."
          else
            echo "Changes detected, attempting commit..."
            # Commit all staged changes (-a might be too broad, rely on explicit add)
            git commit -m "Update LanaCoin analysis results and data"
            echo "Pushing changes..."
            # Push using default GITHUB_TOKEN
            git push
            echo "Changes pushed."
          fi
